### ISSUE TITLE
com.google.code.gson:gson - J2ObjC continuous build

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-common-libs-e2e-test#19]
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/systemTests/externalLibrary1/third_party_gson/build.gradle

Should convert the system tests in j2objc-gradle to an independent continuous build here.

**Comment by brunobowden** [comment]
cc @swankjesse @inder123 - this is an FYI that we've setup a continuous build to translate the Gson library to objective-C to allow it's use on iOS. This uses Google J2ObjC project to greatly extend the sharing of code on the two platforms.

Example build:
https://travis-ci.org/j2objc-contrib/j2objc-common-libs-e2e-test/jobs/82360553

An article about J2ObjC's use for Google's Inbox:
http://arstechnica.com/information-technology/2014/11/how-google-inbox-shares-70-of-its-code-across-android-ios-and-the-web/

**Comment by inder123** [comment]
Wow! Awesome. Can you provide a link to where users can download this
library for use in their iOS projects? I would like to put a link on Gson
project page, and direct people to it on mailing lists.

On Mon, Sep 28, 2015 at 8:04 AM, Bruno Bowden notifications@github.com
wrote:

> cc @swankjesse https://github.com/swankjesse @inder123
> https://github.com/inder123 - this is an FYI that we've setup a
> continuous build to translate the Gson library to objective-C to allow it's
> use on iOS. This uses Google J2ObjC project to greatly extend the sharing
> of code on the two platforms.
> 
> Example build:
> 
> https://travis-ci.org/j2objc-contrib/j2objc-common-libs-e2e-test/jobs/82360553
> 
> An article about J2ObjC's use for Google's Inbox:
> 
> http://arstechnica.com/information-technology/2014/11/how-google-inbox-shares-70-of-its-code-across-android-ios-and-the-web/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/19#issuecomment-143768790
> .

## 

http://www.singhinderjeet.com/

**Comment by brunobowden** [comment]
@inder123 - we don't have any plans to publish pre-compiled libraries. In order to use this, someone will need to do their Android build in Gradle then correctly configure a further gradle for the Gson build. Here's an example for how this project would be done:

https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/blob/master/libraryBuilds/com.google.code.gson-gson/build.gradle

My suggestion is to first try this yourself, so you understand how it works. Likely this process will improve a great deal over the next few releases.
